name: gestion_contacts
description: Application de gestion de contacts
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^13.0.1
  
  # HTTP et API
  http: ^1.1.0
  
  # Gestion de l'Ã©tat local
  #shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true